// Code generated by internal/asmgen. DO NOT EDIT.
//
// sve2vl512 kernels for arm64. Each line is one instruction: the
// bytes were produced by the system assembler from the generator's output,
// and the comment is the disassembly of exactly those bytes.

//go:build !purego

#include "textflag.h"

// func hashLongSVE2VL512(acc *[8]uint64, in unsafe.Pointer, n int, sec unsafe.Pointer, secretLimit int)
//
// consumes a whole long input: blocks, scrambles, trailing stripes and the overlapping final stripe.
TEXT ·hashLongSVE2VL512(SB), NOSPLIT, $0-40
	MOVD acc+0(FP), R0
	MOVD in+8(FP), R1
	MOVD n+16(FP), R2
	MOVD sec+24(FP), R3
	MOVD secretLimit+32(FP), R4
	WORD $0xd28f362c // mov x12, #0x79b1 // #31153
	WORD $0xf2b3c6ec // movk x12, #0x9e37, lsl #16
	WORD $0x05e0398f // mov z15.d, x12
	WORD $0x25d8e3e0 // ptrue p0.d
	WORD $0xa5e0a000 // ld1d {z0.d}, p0/z, [x0]
	WORD $0x25f8c004 // mov z4.d, #0
	WORD $0xaa0103ea // mov x10, x1
	WORD $0x8b02014a // add x10, x10, x2
	WORD $0xd101014a // sub x10, x10, #0x40
	WORD $0xaa0403e6 // mov x6, x4
	WORD $0xd343fcc6 // lsr x6, x6, #3
	WORD $0xd37ae4c6 // lsl x6, x6, #6
	WORD $0xaa0203e7 // mov x7, x2
	WORD $0xd10004e7 // sub x7, x7, #0x1
	// .Lblock1:
	WORD $0xeb0600ff // cmp x7, x6
	WORD $0x5400080b // b.lt 13c <kernel+0x13c> // b.tstop
	WORD $0xaa0403e8 // mov x8, x4
	WORD $0xd343fd08 // lsr x8, x8, #3
	WORD $0xaa0303e9 // mov x9, x3
	WORD $0xf1001108 // subs x8, x8, #0x4
	WORD $0x5400040b // b.lt d0 <kernel+0xd0> // b.tstop
	// .Lunroll3:
	WORD $0xa5e0a030 // ld1d {z16.d}, p0/z, [x1]
	WORD $0xa5e0a131 // ld1d {z17.d}, p0/z, [x9]
	WORD $0x04b13211 // eor z17.d, z16.d, z17.d
	WORD $0x04e09632 // lsr z18.d, z17.d, #32
	WORD $0x44d24a20 // umlalb z0.d, z17.s, z18.s
	WORD $0x04f00084 // add z4.d, z4.d, z16.d
	WORD $0x91002129 // add x9, x9, #0x8
	WORD $0xa5e1a033 // ld1d {z19.d}, p0/z, [x1, #1, mul vl]
	WORD $0xa5e0a134 // ld1d {z20.d}, p0/z, [x9]
	WORD $0x04b43274 // eor z20.d, z19.d, z20.d
	WORD $0x04e09695 // lsr z21.d, z20.d, #32
	WORD $0x44d54a80 // umlalb z0.d, z20.s, z21.s
	WORD $0x04f30084 // add z4.d, z4.d, z19.d
	WORD $0x91002129 // add x9, x9, #0x8
	WORD $0xa5e2a036 // ld1d {z22.d}, p0/z, [x1, #2, mul vl]
	WORD $0xa5e0a137 // ld1d {z23.d}, p0/z, [x9]
	WORD $0x04b732d7 // eor z23.d, z22.d, z23.d
	WORD $0x04e096f8 // lsr z24.d, z23.d, #32
	WORD $0x44d84ae0 // umlalb z0.d, z23.s, z24.s
	WORD $0x04f60084 // add z4.d, z4.d, z22.d
	WORD $0x91002129 // add x9, x9, #0x8
	WORD $0xa5e3a039 // ld1d {z25.d}, p0/z, [x1, #3, mul vl]
	WORD $0xa5e0a13a // ld1d {z26.d}, p0/z, [x9]
	WORD $0x04ba333a // eor z26.d, z25.d, z26.d
	WORD $0x04e0975b // lsr z27.d, z26.d, #32
	WORD $0x44db4b40 // umlalb z0.d, z26.s, z27.s
	WORD $0x04f90084 // add z4.d, z4.d, z25.d
	WORD $0x91002129 // add x9, x9, #0x8
	WORD $0x91040021 // add x1, x1, #0x100
	WORD $0xf1001108 // subs x8, x8, #0x4
	WORD $0x54fffc4a // b.ge 54 <kernel+0x54> // b.tcont
	// .Lone4:
	WORD $0x91001108 // add x8, x8, #0x4
	WORD $0xf100011f // cmp x8, #0x0
	WORD $0x5400016d // b.le 104 <kernel+0x104>
	// .Lonebody6:
	WORD $0xa5e0a030 // ld1d {z16.d}, p0/z, [x1]
	WORD $0xa5e0a131 // ld1d {z17.d}, p0/z, [x9]
	WORD $0x04b13211 // eor z17.d, z16.d, z17.d
	WORD $0x04e09632 // lsr z18.d, z17.d, #32
	WORD $0x44d24a20 // umlalb z0.d, z17.s, z18.s
	WORD $0x04f00084 // add z4.d, z4.d, z16.d
	WORD $0x91010021 // add x1, x1, #0x40
	WORD $0x91002129 // add x9, x9, #0x8
	WORD $0xf1000508 // subs x8, x8, #0x1
	WORD $0x54fffeec // b.gt dc <kernel+0xdc>
	// .Ldone5:
	WORD $0x05e47490 // trn2 z16.d, z4.d, z4.d
	WORD $0x05e4709f // trn1 z31.d, z4.d, z4.d
	WORD $0x05ff7210 // trn1 z16.d, z16.d, z31.d
	WORD $0x04f00000 // add z0.d, z0.d, z16.d
	WORD $0x25f8c004 // mov z4.d, #0
	WORD $0xaa0303eb // mov x11, x3
	WORD $0x8b04016b // add x11, x11, x4
	WORD $0x04b19410 // lsr z16.d, z0.d, #47
	WORD $0x04b03000 // eor z0.d, z0.d, z16.d
	WORD $0xa5e0a170 // ld1d {z16.d}, p0/z, [x11]
	WORD $0x04b03000 // eor z0.d, z0.d, z16.d
	WORD $0x04ef6000 // mul z0.d, z0.d, z15.d
	WORD $0xcb0600e7 // sub x7, x7, x6
	WORD $0x17ffffc0 // b 38 <kernel+0x38>
	// .Ltail2:
	WORD $0xaa0703e8 // mov x8, x7
	WORD $0xd346fd08 // lsr x8, x8, #6
	WORD $0xaa0303e9 // mov x9, x3
	WORD $0xf1001108 // subs x8, x8, #0x4
	WORD $0x5400040b // b.lt 1cc <kernel+0x1cc> // b.tstop
	// .Lunroll7:
	WORD $0xa5e0a030 // ld1d {z16.d}, p0/z, [x1]
	WORD $0xa5e0a131 // ld1d {z17.d}, p0/z, [x9]
	WORD $0x04b13211 // eor z17.d, z16.d, z17.d
	WORD $0x04e09632 // lsr z18.d, z17.d, #32
	WORD $0x44d24a20 // umlalb z0.d, z17.s, z18.s
	WORD $0x04f00084 // add z4.d, z4.d, z16.d
	WORD $0x91002129 // add x9, x9, #0x8
	WORD $0xa5e1a033 // ld1d {z19.d}, p0/z, [x1, #1, mul vl]
	WORD $0xa5e0a134 // ld1d {z20.d}, p0/z, [x9]
	WORD $0x04b43274 // eor z20.d, z19.d, z20.d
	WORD $0x04e09695 // lsr z21.d, z20.d, #32
	WORD $0x44d54a80 // umlalb z0.d, z20.s, z21.s
	WORD $0x04f30084 // add z4.d, z4.d, z19.d
	WORD $0x91002129 // add x9, x9, #0x8
	WORD $0xa5e2a036 // ld1d {z22.d}, p0/z, [x1, #2, mul vl]
	WORD $0xa5e0a137 // ld1d {z23.d}, p0/z, [x9]
	WORD $0x04b732d7 // eor z23.d, z22.d, z23.d
	WORD $0x04e096f8 // lsr z24.d, z23.d, #32
	WORD $0x44d84ae0 // umlalb z0.d, z23.s, z24.s
	WORD $0x04f60084 // add z4.d, z4.d, z22.d
	WORD $0x91002129 // add x9, x9, #0x8
	WORD $0xa5e3a039 // ld1d {z25.d}, p0/z, [x1, #3, mul vl]
	WORD $0xa5e0a13a // ld1d {z26.d}, p0/z, [x9]
	WORD $0x04ba333a // eor z26.d, z25.d, z26.d
	WORD $0x04e0975b // lsr z27.d, z26.d, #32
	WORD $0x44db4b40 // umlalb z0.d, z26.s, z27.s
	WORD $0x04f90084 // add z4.d, z4.d, z25.d
	WORD $0x91002129 // add x9, x9, #0x8
	WORD $0x91040021 // add x1, x1, #0x100
	WORD $0xf1001108 // subs x8, x8, #0x4
	WORD $0x54fffc4a // b.ge 150 <kernel+0x150> // b.tcont
	// .Lone8:
	WORD $0x91001108 // add x8, x8, #0x4
	WORD $0xf100011f // cmp x8, #0x0
	WORD $0x5400016d // b.le 200 <kernel+0x200>
	// .Lonebody10:
	WORD $0xa5e0a030 // ld1d {z16.d}, p0/z, [x1]
	WORD $0xa5e0a131 // ld1d {z17.d}, p0/z, [x9]
	WORD $0x04b13211 // eor z17.d, z16.d, z17.d
	WORD $0x04e09632 // lsr z18.d, z17.d, #32
	WORD $0x44d24a20 // umlalb z0.d, z17.s, z18.s
	WORD $0x04f00084 // add z4.d, z4.d, z16.d
	WORD $0x91010021 // add x1, x1, #0x40
	WORD $0x91002129 // add x9, x9, #0x8
	WORD $0xf1000508 // subs x8, x8, #0x1
	WORD $0x54fffeec // b.gt 1d8 <kernel+0x1d8>
	// .Ldone9:
	WORD $0xaa0303eb // mov x11, x3
	WORD $0x8b04016b // add x11, x11, x4
	WORD $0xd1001d6b // sub x11, x11, #0x7
	WORD $0xa5e0a150 // ld1d {z16.d}, p0/z, [x10]
	WORD $0xa5e0a171 // ld1d {z17.d}, p0/z, [x11]
	WORD $0x04b13211 // eor z17.d, z16.d, z17.d
	WORD $0x04e09632 // lsr z18.d, z17.d, #32
	WORD $0x44d24a20 // umlalb z0.d, z17.s, z18.s
	WORD $0x04f00084 // add z4.d, z4.d, z16.d
	WORD $0x05e47490 // trn2 z16.d, z4.d, z4.d
	WORD $0x05e4709f // trn1 z31.d, z4.d, z4.d
	WORD $0x05ff7210 // trn1 z16.d, z16.d, z31.d
	WORD $0x04f00000 // add z0.d, z0.d, z16.d
	WORD $0xe5e0e000 // st1d {z0.d}, p0, [x0]
	RET

// func accumBlocksSVE2VL512(acc *[8]uint64, in unsafe.Pointer, nbStripes int, sec unsafe.Pointer, secretLimit int, soFar int)
//
// absorbs nbStripes stripes starting soFar stripes into the current block, scrambling at every block boundary it crosses.
TEXT ·accumBlocksSVE2VL512(SB), NOSPLIT, $0-48
	MOVD acc+0(FP), R0
	MOVD in+8(FP), R1
	MOVD nbStripes+16(FP), R2
	MOVD sec+24(FP), R3
	MOVD secretLimit+32(FP), R4
	MOVD soFar+40(FP), R5
	WORD $0xd28f362c // mov x12, #0x79b1 // #31153
	WORD $0xf2b3c6ec // movk x12, #0x9e37, lsl #16
	WORD $0x05e0398f // mov z15.d, x12
	WORD $0x25d8e3e0 // ptrue p0.d
	WORD $0xa5e0a000 // ld1d {z0.d}, p0/z, [x0]
	WORD $0x25f8c004 // mov z4.d, #0
	WORD $0xaa0403e6 // mov x6, x4
	WORD $0xd343fcc6 // lsr x6, x6, #3
	WORD $0xaa0503e7 // mov x7, x5
	WORD $0xd37df0e7 // lsl x7, x7, #3
	WORD $0x8b0300e7 // add x7, x7, x3
	WORD $0xaa0603e8 // mov x8, x6
	WORD $0xcb050108 // sub x8, x8, x5
	// .Lblocks1:
	WORD $0xf100005f // cmp x2, #0x0
	WORD $0x540008cd // b.le 150 <kernel+0x150>
	WORD $0xaa0803e9 // mov x9, x8
	WORD $0xeb02013f // cmp x9, x2
	WORD $0x5400004d // b.le 4c <kernel+0x4c>
	WORD $0xaa0203e9 // mov x9, x2
	// .Lmin3:
	WORD $0xcb090042 // sub x2, x2, x9
	WORD $0xaa0903ea // mov x10, x9
	WORD $0xf1001129 // subs x9, x9, #0x4
	WORD $0x5400040b // b.lt d8 <kernel+0xd8> // b.tstop
	// .Lunroll4:
	WORD $0xa5e0a030 // ld1d {z16.d}, p0/z, [x1]
	WORD $0xa5e0a0f1 // ld1d {z17.d}, p0/z, [x7]
	WORD $0x04b13211 // eor z17.d, z16.d, z17.d
	WORD $0x04e09632 // lsr z18.d, z17.d, #32
	WORD $0x44d24a20 // umlalb z0.d, z17.s, z18.s
	WORD $0x04f00084 // add z4.d, z4.d, z16.d
	WORD $0x910020e7 // add x7, x7, #0x8
	WORD $0xa5e1a033 // ld1d {z19.d}, p0/z, [x1, #1, mul vl]
	WORD $0xa5e0a0f4 // ld1d {z20.d}, p0/z, [x7]
	WORD $0x04b43274 // eor z20.d, z19.d, z20.d
	WORD $0x04e09695 // lsr z21.d, z20.d, #32
	WORD $0x44d54a80 // umlalb z0.d, z20.s, z21.s
	WORD $0x04f30084 // add z4.d, z4.d, z19.d
	WORD $0x910020e7 // add x7, x7, #0x8
	WORD $0xa5e2a036 // ld1d {z22.d}, p0/z, [x1, #2, mul vl]
	WORD $0xa5e0a0f7 // ld1d {z23.d}, p0/z, [x7]
	WORD $0x04b732d7 // eor z23.d, z22.d, z23.d
	WORD $0x04e096f8 // lsr z24.d, z23.d, #32
	WORD $0x44d84ae0 // umlalb z0.d, z23.s, z24.s
	WORD $0x04f60084 // add z4.d, z4.d, z22.d
	WORD $0x910020e7 // add x7, x7, #0x8
	WORD $0xa5e3a039 // ld1d {z25.d}, p0/z, [x1, #3, mul vl]
	WORD $0xa5e0a0fa // ld1d {z26.d}, p0/z, [x7]
	WORD $0x04ba333a // eor z26.d, z25.d, z26.d
	WORD $0x04e0975b // lsr z27.d, z26.d, #32
	WORD $0x44db4b40 // umlalb z0.d, z26.s, z27.s
	WORD $0x04f90084 // add z4.d, z4.d, z25.d
	WORD $0x910020e7 // add x7, x7, #0x8
	WORD $0x91040021 // add x1, x1, #0x100
	WORD $0xf1001129 // subs x9, x9, #0x4
	WORD $0x54fffc4a // b.ge 5c <kernel+0x5c> // b.tcont
	// .Lone5:
	WORD $0x91001129 // add x9, x9, #0x4
	WORD $0xf100013f // cmp x9, #0x0
	WORD $0x5400016d // b.le 10c <kernel+0x10c>
	// .Lonebody7:
	WORD $0xa5e0a030 // ld1d {z16.d}, p0/z, [x1]
	WORD $0xa5e0a0f1 // ld1d {z17.d}, p0/z, [x7]
	WORD $0x04b13211 // eor z17.d, z16.d, z17.d
	WORD $0x04e09632 // lsr z18.d, z17.d, #32
	WORD $0x44d24a20 // umlalb z0.d, z17.s, z18.s
	WORD $0x04f00084 // add z4.d, z4.d, z16.d
	WORD $0x91010021 // add x1, x1, #0x40
	WORD $0x910020e7 // add x7, x7, #0x8
	WORD $0xf1000529 // subs x9, x9, #0x1
	WORD $0x54fffeec // b.gt e4 <kernel+0xe4>
	// .Ldone6:
	WORD $0xeb08015f // cmp x10, x8
	WORD $0x54000201 // b.ne 150 <kernel+0x150> // b.any
	WORD $0x05e47490 // trn2 z16.d, z4.d, z4.d
	WORD $0x05e4709f // trn1 z31.d, z4.d, z4.d
	WORD $0x05ff7210 // trn1 z16.d, z16.d, z31.d
	WORD $0x04f00000 // add z0.d, z0.d, z16.d
	WORD $0x25f8c004 // mov z4.d, #0
	WORD $0xaa0303ea // mov x10, x3
	WORD $0x8b04014a // add x10, x10, x4
	WORD $0x04b19410 // lsr z16.d, z0.d, #47
	WORD $0x04b03000 // eor z0.d, z0.d, z16.d
	WORD $0xa5e0a150 // ld1d {z16.d}, p0/z, [x10]
	WORD $0x04b03000 // eor z0.d, z0.d, z16.d
	WORD $0x04ef6000 // mul z0.d, z0.d, z15.d
	WORD $0xaa0303e7 // mov x7, x3
	WORD $0xaa0603e8 // mov x8, x6
	WORD $0x17ffffba // b 34 <kernel+0x34>
	// .Lbdone2:
	WORD $0x05e47490 // trn2 z16.d, z4.d, z4.d
	WORD $0x05e4709f // trn1 z31.d, z4.d, z4.d
	WORD $0x05ff7210 // trn1 z16.d, z16.d, z31.d
	WORD $0x04f00000 // add z0.d, z0.d, z16.d
	WORD $0xe5e0e000 // st1d {z0.d}, p0, [x0]
	RET

// func accumSVE2VL512(acc *[8]uint64, in unsafe.Pointer, nbStripes int, sec unsafe.Pointer)
//
// absorbs nbStripes consecutive stripes against one secret position, with no scramble.
TEXT ·accumSVE2VL512(SB), NOSPLIT, $0-32
	MOVD acc+0(FP), R0
	MOVD in+8(FP), R1
	MOVD nbStripes+16(FP), R2
	MOVD sec+24(FP), R3
	WORD $0x25d8e3e0 // ptrue p0.d
	WORD $0xa5e0a000 // ld1d {z0.d}, p0/z, [x0]
	WORD $0x25f8c004 // mov z4.d, #0
	WORD $0xaa0303e6 // mov x6, x3
	WORD $0xf1001042 // subs x2, x2, #0x4
	WORD $0x5400040b // b.lt 94 <kernel+0x94> // b.tstop
	// .Lunroll1:
	WORD $0xa5e0a030 // ld1d {z16.d}, p0/z, [x1]
	WORD $0xa5e0a0d1 // ld1d {z17.d}, p0/z, [x6]
	WORD $0x04b13211 // eor z17.d, z16.d, z17.d
	WORD $0x04e09632 // lsr z18.d, z17.d, #32
	WORD $0x44d24a20 // umlalb z0.d, z17.s, z18.s
	WORD $0x04f00084 // add z4.d, z4.d, z16.d
	WORD $0x910020c6 // add x6, x6, #0x8
	WORD $0xa5e1a033 // ld1d {z19.d}, p0/z, [x1, #1, mul vl]
	WORD $0xa5e0a0d4 // ld1d {z20.d}, p0/z, [x6]
	WORD $0x04b43274 // eor z20.d, z19.d, z20.d
	WORD $0x04e09695 // lsr z21.d, z20.d, #32
	WORD $0x44d54a80 // umlalb z0.d, z20.s, z21.s
	WORD $0x04f30084 // add z4.d, z4.d, z19.d
	WORD $0x910020c6 // add x6, x6, #0x8
	WORD $0xa5e2a036 // ld1d {z22.d}, p0/z, [x1, #2, mul vl]
	WORD $0xa5e0a0d7 // ld1d {z23.d}, p0/z, [x6]
	WORD $0x04b732d7 // eor z23.d, z22.d, z23.d
	WORD $0x04e096f8 // lsr z24.d, z23.d, #32
	WORD $0x44d84ae0 // umlalb z0.d, z23.s, z24.s
	WORD $0x04f60084 // add z4.d, z4.d, z22.d
	WORD $0x910020c6 // add x6, x6, #0x8
	WORD $0xa5e3a039 // ld1d {z25.d}, p0/z, [x1, #3, mul vl]
	WORD $0xa5e0a0da // ld1d {z26.d}, p0/z, [x6]
	WORD $0x04ba333a // eor z26.d, z25.d, z26.d
	WORD $0x04e0975b // lsr z27.d, z26.d, #32
	WORD $0x44db4b40 // umlalb z0.d, z26.s, z27.s
	WORD $0x04f90084 // add z4.d, z4.d, z25.d
	WORD $0x910020c6 // add x6, x6, #0x8
	WORD $0x91040021 // add x1, x1, #0x100
	WORD $0xf1001042 // subs x2, x2, #0x4
	WORD $0x54fffc4a // b.ge 18 <kernel+0x18> // b.tcont
	// .Lone2:
	WORD $0x91001042 // add x2, x2, #0x4
	WORD $0xf100005f // cmp x2, #0x0
	WORD $0x5400016d // b.le c8 <kernel+0xc8>
	// .Lonebody4:
	WORD $0xa5e0a030 // ld1d {z16.d}, p0/z, [x1]
	WORD $0xa5e0a0d1 // ld1d {z17.d}, p0/z, [x6]
	WORD $0x04b13211 // eor z17.d, z16.d, z17.d
	WORD $0x04e09632 // lsr z18.d, z17.d, #32
	WORD $0x44d24a20 // umlalb z0.d, z17.s, z18.s
	WORD $0x04f00084 // add z4.d, z4.d, z16.d
	WORD $0x91010021 // add x1, x1, #0x40
	WORD $0x910020c6 // add x6, x6, #0x8
	WORD $0xf1000442 // subs x2, x2, #0x1
	WORD $0x54fffeec // b.gt a0 <kernel+0xa0>
	// .Ldone3:
	WORD $0x05e47490 // trn2 z16.d, z4.d, z4.d
	WORD $0x05e4709f // trn1 z31.d, z4.d, z4.d
	WORD $0x05ff7210 // trn1 z16.d, z16.d, z31.d
	WORD $0x04f00000 // add z0.d, z0.d, z16.d
	WORD $0xe5e0e000 // st1d {z0.d}, p0, [x0]
	RET
