// Code generated by internal/asmgen. DO NOT EDIT.

//go:build !purego

package xxhaste

import "unsafe"

// Declarations for the arm64 kernels in the .s files beside this one.
// Which of them runs is decided in dispatch_arm64.go.

// hashLongNEON consumes a whole long input: blocks, scrambles, trailing stripes and the overlapping final stripe.
//
//go:noescape
func hashLongNEON(acc *[8]uint64, in unsafe.Pointer, n int, sec unsafe.Pointer, secretLimit int)

// accumBlocksNEON absorbs nbStripes stripes starting soFar stripes into the current block, scrambling at every block boundary it crosses.
//
//go:noescape
func accumBlocksNEON(acc *[8]uint64, in unsafe.Pointer, nbStripes int, sec unsafe.Pointer, secretLimit int, soFar int)

// accumNEON absorbs nbStripes consecutive stripes against one secret position, with no scramble.
//
//go:noescape
func accumNEON(acc *[8]uint64, in unsafe.Pointer, nbStripes int, sec unsafe.Pointer)

// hashLongSVE2VL128 consumes a whole long input: blocks, scrambles, trailing stripes and the overlapping final stripe.
//
//go:noescape
func hashLongSVE2VL128(acc *[8]uint64, in unsafe.Pointer, n int, sec unsafe.Pointer, secretLimit int)

// accumBlocksSVE2VL128 absorbs nbStripes stripes starting soFar stripes into the current block, scrambling at every block boundary it crosses.
//
//go:noescape
func accumBlocksSVE2VL128(acc *[8]uint64, in unsafe.Pointer, nbStripes int, sec unsafe.Pointer, secretLimit int, soFar int)

// accumSVE2VL128 absorbs nbStripes consecutive stripes against one secret position, with no scramble.
//
//go:noescape
func accumSVE2VL128(acc *[8]uint64, in unsafe.Pointer, nbStripes int, sec unsafe.Pointer)

// hashLongSVE2VL256 consumes a whole long input: blocks, scrambles, trailing stripes and the overlapping final stripe.
//
//go:noescape
func hashLongSVE2VL256(acc *[8]uint64, in unsafe.Pointer, n int, sec unsafe.Pointer, secretLimit int)

// accumBlocksSVE2VL256 absorbs nbStripes stripes starting soFar stripes into the current block, scrambling at every block boundary it crosses.
//
//go:noescape
func accumBlocksSVE2VL256(acc *[8]uint64, in unsafe.Pointer, nbStripes int, sec unsafe.Pointer, secretLimit int, soFar int)

// accumSVE2VL256 absorbs nbStripes consecutive stripes against one secret position, with no scramble.
//
//go:noescape
func accumSVE2VL256(acc *[8]uint64, in unsafe.Pointer, nbStripes int, sec unsafe.Pointer)

// hashLongSVE2VL512 consumes a whole long input: blocks, scrambles, trailing stripes and the overlapping final stripe.
//
//go:noescape
func hashLongSVE2VL512(acc *[8]uint64, in unsafe.Pointer, n int, sec unsafe.Pointer, secretLimit int)

// accumBlocksSVE2VL512 absorbs nbStripes stripes starting soFar stripes into the current block, scrambling at every block boundary it crosses.
//
//go:noescape
func accumBlocksSVE2VL512(acc *[8]uint64, in unsafe.Pointer, nbStripes int, sec unsafe.Pointer, secretLimit int, soFar int)

// accumSVE2VL512 absorbs nbStripes consecutive stripes against one secret position, with no scramble.
//
//go:noescape
func accumSVE2VL512(acc *[8]uint64, in unsafe.Pointer, nbStripes int, sec unsafe.Pointer)
