// Code generated by internal/asmgen. DO NOT EDIT.
//
// sve2vl512 kernels for arm64. Each line is one instruction: the
// bytes were produced by the system assembler from the generator's output,
// and the comment is the disassembly of exactly those bytes.

//go:build !purego

#include "textflag.h"

// func hashLongSVE2VL512(acc *[8]uint64, in unsafe.Pointer, n int, sec unsafe.Pointer, secretLimit int)
//
// consumes a whole long input: blocks, scrambles, trailing stripes and the overlapping final stripe.
TEXT ·hashLongSVE2VL512(SB), NOSPLIT, $0-40
	MOVD acc+0(FP), R0
	MOVD in+8(FP), R1
	MOVD n+16(FP), R2
	MOVD sec+24(FP), R3
	MOVD secretLimit+32(FP), R4
	WORD $0xd28f362b // mov x11, #0x79b1 // #31153
	WORD $0xf2b3c6eb // movk x11, #0x9e37, lsl #16
	WORD $0x05e0396f // mov z15.d, x11
	WORD $0x25d8e3e0 // ptrue p0.d
	WORD $0xa5e0a000 // ld1d {z0.d}, p0/z, [x0]
	WORD $0x25f8c004 // mov z4.d, #0
	WORD $0xaa0103e9 // mov x9, x1
	WORD $0x8b020129 // add x9, x9, x2
	WORD $0xd1010129 // sub x9, x9, #0x40
	WORD $0xaa0403e5 // mov x5, x4
	WORD $0xd343fca5 // lsr x5, x5, #3
	WORD $0xd37ae4a5 // lsl x5, x5, #6
	WORD $0xaa0203e6 // mov x6, x2
	WORD $0xd10004c6 // sub x6, x6, #0x1
	// .Lblock1:
	WORD $0xeb0500df // cmp x6, x5
	WORD $0x5400082b // b.lt 140 <kernel+0x140> // b.tstop
	WORD $0xaa0403e7 // mov x7, x4
	WORD $0xd343fce7 // lsr x7, x7, #3
	WORD $0xaa0303e8 // mov x8, x3
	WORD $0xf10010ff // cmp x7, #0x4
	WORD $0x5400042b // b.lt d4 <kernel+0xd4> // b.tstop
	// .Lunroll3:
	WORD $0xa5e0a030 // ld1d {z16.d}, p0/z, [x1]
	WORD $0xa5e0a111 // ld1d {z17.d}, p0/z, [x8]
	WORD $0x04b13211 // eor z17.d, z16.d, z17.d
	WORD $0x04e09632 // lsr z18.d, z17.d, #32
	WORD $0x44d24a20 // umlalb z0.d, z17.s, z18.s
	WORD $0x04f00084 // add z4.d, z4.d, z16.d
	WORD $0x91002108 // add x8, x8, #0x8
	WORD $0xa5e1a033 // ld1d {z19.d}, p0/z, [x1, #1, mul vl]
	WORD $0xa5e0a114 // ld1d {z20.d}, p0/z, [x8]
	WORD $0x04b43274 // eor z20.d, z19.d, z20.d
	WORD $0x04e09695 // lsr z21.d, z20.d, #32
	WORD $0x44d54a80 // umlalb z0.d, z20.s, z21.s
	WORD $0x04f30084 // add z4.d, z4.d, z19.d
	WORD $0x91002108 // add x8, x8, #0x8
	WORD $0xa5e2a036 // ld1d {z22.d}, p0/z, [x1, #2, mul vl]
	WORD $0xa5e0a117 // ld1d {z23.d}, p0/z, [x8]
	WORD $0x04b732d7 // eor z23.d, z22.d, z23.d
	WORD $0x04e096f8 // lsr z24.d, z23.d, #32
	WORD $0x44d84ae0 // umlalb z0.d, z23.s, z24.s
	WORD $0x04f60084 // add z4.d, z4.d, z22.d
	WORD $0x91002108 // add x8, x8, #0x8
	WORD $0xa5e3a039 // ld1d {z25.d}, p0/z, [x1, #3, mul vl]
	WORD $0xa5e0a11a // ld1d {z26.d}, p0/z, [x8]
	WORD $0x04ba333a // eor z26.d, z25.d, z26.d
	WORD $0x04e0975b // lsr z27.d, z26.d, #32
	WORD $0x44db4b40 // umlalb z0.d, z26.s, z27.s
	WORD $0x04f90084 // add z4.d, z4.d, z25.d
	WORD $0x91002108 // add x8, x8, #0x8
	WORD $0x91040021 // add x1, x1, #0x100
	WORD $0xd10010e7 // sub x7, x7, #0x4
	WORD $0xf10010ff // cmp x7, #0x4
	WORD $0x54fffc2a // b.ge 54 <kernel+0x54> // b.tcont
	// .Lone4:
	WORD $0xf10000ff // cmp x7, #0x0
	WORD $0x5400018d // b.le 108 <kernel+0x108>
	// .Lonebody6:
	WORD $0xa5e0a030 // ld1d {z16.d}, p0/z, [x1]
	WORD $0xa5e0a111 // ld1d {z17.d}, p0/z, [x8]
	WORD $0x04b13211 // eor z17.d, z16.d, z17.d
	WORD $0x04e09632 // lsr z18.d, z17.d, #32
	WORD $0x44d24a20 // umlalb z0.d, z17.s, z18.s
	WORD $0x04f00084 // add z4.d, z4.d, z16.d
	WORD $0x91010021 // add x1, x1, #0x40
	WORD $0x91002108 // add x8, x8, #0x8
	WORD $0xd10004e7 // sub x7, x7, #0x1
	WORD $0xf10000ff // cmp x7, #0x0
	WORD $0x54fffecc // b.gt dc <kernel+0xdc>
	// .Ldone5:
	WORD $0x05e47490 // trn2 z16.d, z4.d, z4.d
	WORD $0x05e4709f // trn1 z31.d, z4.d, z4.d
	WORD $0x05ff7210 // trn1 z16.d, z16.d, z31.d
	WORD $0x04f00000 // add z0.d, z0.d, z16.d
	WORD $0x25f8c004 // mov z4.d, #0
	WORD $0xaa0303ea // mov x10, x3
	WORD $0x8b04014a // add x10, x10, x4
	WORD $0x04b19410 // lsr z16.d, z0.d, #47
	WORD $0x04b03000 // eor z0.d, z0.d, z16.d
	WORD $0xa5e0a150 // ld1d {z16.d}, p0/z, [x10]
	WORD $0x04b03000 // eor z0.d, z0.d, z16.d
	WORD $0x04ef6000 // mul z0.d, z0.d, z15.d
	WORD $0xcb0500c6 // sub x6, x6, x5
	WORD $0x17ffffbf // b 38 <kernel+0x38>
	// .Ltail2:
	WORD $0xaa0603e7 // mov x7, x6
	WORD $0xd346fce7 // lsr x7, x7, #6
	WORD $0xaa0303e8 // mov x8, x3
	WORD $0xf10010ff // cmp x7, #0x4
	WORD $0x5400042b // b.lt 1d4 <kernel+0x1d4> // b.tstop
	// .Lunroll7:
	WORD $0xa5e0a030 // ld1d {z16.d}, p0/z, [x1]
	WORD $0xa5e0a111 // ld1d {z17.d}, p0/z, [x8]
	WORD $0x04b13211 // eor z17.d, z16.d, z17.d
	WORD $0x04e09632 // lsr z18.d, z17.d, #32
	WORD $0x44d24a20 // umlalb z0.d, z17.s, z18.s
	WORD $0x04f00084 // add z4.d, z4.d, z16.d
	WORD $0x91002108 // add x8, x8, #0x8
	WORD $0xa5e1a033 // ld1d {z19.d}, p0/z, [x1, #1, mul vl]
	WORD $0xa5e0a114 // ld1d {z20.d}, p0/z, [x8]
	WORD $0x04b43274 // eor z20.d, z19.d, z20.d
	WORD $0x04e09695 // lsr z21.d, z20.d, #32
	WORD $0x44d54a80 // umlalb z0.d, z20.s, z21.s
	WORD $0x04f30084 // add z4.d, z4.d, z19.d
	WORD $0x91002108 // add x8, x8, #0x8
	WORD $0xa5e2a036 // ld1d {z22.d}, p0/z, [x1, #2, mul vl]
	WORD $0xa5e0a117 // ld1d {z23.d}, p0/z, [x8]
	WORD $0x04b732d7 // eor z23.d, z22.d, z23.d
	WORD $0x04e096f8 // lsr z24.d, z23.d, #32
	WORD $0x44d84ae0 // umlalb z0.d, z23.s, z24.s
	WORD $0x04f60084 // add z4.d, z4.d, z22.d
	WORD $0x91002108 // add x8, x8, #0x8
	WORD $0xa5e3a039 // ld1d {z25.d}, p0/z, [x1, #3, mul vl]
	WORD $0xa5e0a11a // ld1d {z26.d}, p0/z, [x8]
	WORD $0x04ba333a // eor z26.d, z25.d, z26.d
	WORD $0x04e0975b // lsr z27.d, z26.d, #32
	WORD $0x44db4b40 // umlalb z0.d, z26.s, z27.s
	WORD $0x04f90084 // add z4.d, z4.d, z25.d
	WORD $0x91002108 // add x8, x8, #0x8
	WORD $0x91040021 // add x1, x1, #0x100
	WORD $0xd10010e7 // sub x7, x7, #0x4
	WORD $0xf10010ff // cmp x7, #0x4
	WORD $0x54fffc2a // b.ge 154 <kernel+0x154> // b.tcont
	// .Lone8:
	WORD $0xf10000ff // cmp x7, #0x0
	WORD $0x5400018d // b.le 208 <kernel+0x208>
	// .Lonebody10:
	WORD $0xa5e0a030 // ld1d {z16.d}, p0/z, [x1]
	WORD $0xa5e0a111 // ld1d {z17.d}, p0/z, [x8]
	WORD $0x04b13211 // eor z17.d, z16.d, z17.d
	WORD $0x04e09632 // lsr z18.d, z17.d, #32
	WORD $0x44d24a20 // umlalb z0.d, z17.s, z18.s
	WORD $0x04f00084 // add z4.d, z4.d, z16.d
	WORD $0x91010021 // add x1, x1, #0x40
	WORD $0x91002108 // add x8, x8, #0x8
	WORD $0xd10004e7 // sub x7, x7, #0x1
	WORD $0xf10000ff // cmp x7, #0x0
	WORD $0x54fffecc // b.gt 1dc <kernel+0x1dc>
	// .Ldone9:
	WORD $0xaa0303ea // mov x10, x3
	WORD $0x8b04014a // add x10, x10, x4
	WORD $0xd1001d4a // sub x10, x10, #0x7
	WORD $0xa5e0a130 // ld1d {z16.d}, p0/z, [x9]
	WORD $0xa5e0a151 // ld1d {z17.d}, p0/z, [x10]
	WORD $0x04b13211 // eor z17.d, z16.d, z17.d
	WORD $0x04e09632 // lsr z18.d, z17.d, #32
	WORD $0x44d24a20 // umlalb z0.d, z17.s, z18.s
	WORD $0x04f00084 // add z4.d, z4.d, z16.d
	WORD $0x05e47490 // trn2 z16.d, z4.d, z4.d
	WORD $0x05e4709f // trn1 z31.d, z4.d, z4.d
	WORD $0x05ff7210 // trn1 z16.d, z16.d, z31.d
	WORD $0x04f00000 // add z0.d, z0.d, z16.d
	WORD $0x25f8c004 // mov z4.d, #0
	WORD $0xe5e0e000 // st1d {z0.d}, p0, [x0]
	RET

// func accumSVE2VL512(acc *[8]uint64, in unsafe.Pointer, nbStripes int, sec unsafe.Pointer)
//
// absorbs nbStripes consecutive stripes, for the streaming path.
TEXT ·accumSVE2VL512(SB), NOSPLIT, $0-32
	MOVD acc+0(FP), R0
	MOVD in+8(FP), R1
	MOVD nbStripes+16(FP), R2
	MOVD sec+24(FP), R3
	WORD $0xd28f362b // mov x11, #0x79b1 // #31153
	WORD $0xf2b3c6eb // movk x11, #0x9e37, lsl #16
	WORD $0x05e0396f // mov z15.d, x11
	WORD $0x25d8e3e0 // ptrue p0.d
	WORD $0xa5e0a000 // ld1d {z0.d}, p0/z, [x0]
	WORD $0x25f8c004 // mov z4.d, #0
	WORD $0xaa0303e5 // mov x5, x3
	WORD $0xf100105f // cmp x2, #0x4
	WORD $0x5400042b // b.lt a4 <kernel+0xa4> // b.tstop
	// .Lunroll1:
	WORD $0xa5e0a030 // ld1d {z16.d}, p0/z, [x1]
	WORD $0xa5e0a0b1 // ld1d {z17.d}, p0/z, [x5]
	WORD $0x04b13211 // eor z17.d, z16.d, z17.d
	WORD $0x04e09632 // lsr z18.d, z17.d, #32
	WORD $0x44d24a20 // umlalb z0.d, z17.s, z18.s
	WORD $0x04f00084 // add z4.d, z4.d, z16.d
	WORD $0x910020a5 // add x5, x5, #0x8
	WORD $0xa5e1a033 // ld1d {z19.d}, p0/z, [x1, #1, mul vl]
	WORD $0xa5e0a0b4 // ld1d {z20.d}, p0/z, [x5]
	WORD $0x04b43274 // eor z20.d, z19.d, z20.d
	WORD $0x04e09695 // lsr z21.d, z20.d, #32
	WORD $0x44d54a80 // umlalb z0.d, z20.s, z21.s
	WORD $0x04f30084 // add z4.d, z4.d, z19.d
	WORD $0x910020a5 // add x5, x5, #0x8
	WORD $0xa5e2a036 // ld1d {z22.d}, p0/z, [x1, #2, mul vl]
	WORD $0xa5e0a0b7 // ld1d {z23.d}, p0/z, [x5]
	WORD $0x04b732d7 // eor z23.d, z22.d, z23.d
	WORD $0x04e096f8 // lsr z24.d, z23.d, #32
	WORD $0x44d84ae0 // umlalb z0.d, z23.s, z24.s
	WORD $0x04f60084 // add z4.d, z4.d, z22.d
	WORD $0x910020a5 // add x5, x5, #0x8
	WORD $0xa5e3a039 // ld1d {z25.d}, p0/z, [x1, #3, mul vl]
	WORD $0xa5e0a0ba // ld1d {z26.d}, p0/z, [x5]
	WORD $0x04ba333a // eor z26.d, z25.d, z26.d
	WORD $0x04e0975b // lsr z27.d, z26.d, #32
	WORD $0x44db4b40 // umlalb z0.d, z26.s, z27.s
	WORD $0x04f90084 // add z4.d, z4.d, z25.d
	WORD $0x910020a5 // add x5, x5, #0x8
	WORD $0x91040021 // add x1, x1, #0x100
	WORD $0xd1001042 // sub x2, x2, #0x4
	WORD $0xf100105f // cmp x2, #0x4
	WORD $0x54fffc2a // b.ge 24 <kernel+0x24> // b.tcont
	// .Lone2:
	WORD $0xf100005f // cmp x2, #0x0
	WORD $0x5400018d // b.le d8 <kernel+0xd8>
	// .Lonebody4:
	WORD $0xa5e0a030 // ld1d {z16.d}, p0/z, [x1]
	WORD $0xa5e0a0b1 // ld1d {z17.d}, p0/z, [x5]
	WORD $0x04b13211 // eor z17.d, z16.d, z17.d
	WORD $0x04e09632 // lsr z18.d, z17.d, #32
	WORD $0x44d24a20 // umlalb z0.d, z17.s, z18.s
	WORD $0x04f00084 // add z4.d, z4.d, z16.d
	WORD $0x91010021 // add x1, x1, #0x40
	WORD $0x910020a5 // add x5, x5, #0x8
	WORD $0xd1000442 // sub x2, x2, #0x1
	WORD $0xf100005f // cmp x2, #0x0
	WORD $0x54fffecc // b.gt ac <kernel+0xac>
	// .Ldone3:
	WORD $0x05e47490 // trn2 z16.d, z4.d, z4.d
	WORD $0x05e4709f // trn1 z31.d, z4.d, z4.d
	WORD $0x05ff7210 // trn1 z16.d, z16.d, z31.d
	WORD $0x04f00000 // add z0.d, z0.d, z16.d
	WORD $0x25f8c004 // mov z4.d, #0
	WORD $0xe5e0e000 // st1d {z0.d}, p0, [x0]
	RET

// func scrambleSVE2VL512(acc *[8]uint64, sec unsafe.Pointer)
//
// applies the between-blocks accumulator scramble.
TEXT ·scrambleSVE2VL512(SB), NOSPLIT, $0-16
	MOVD acc+0(FP), R0
	MOVD sec+8(FP), R1
	WORD $0xd28f362b // mov x11, #0x79b1 // #31153
	WORD $0xf2b3c6eb // movk x11, #0x9e37, lsl #16
	WORD $0x05e0396f // mov z15.d, x11
	WORD $0x25d8e3e0 // ptrue p0.d
	WORD $0xa5e0a000 // ld1d {z0.d}, p0/z, [x0]
	WORD $0x25f8c004 // mov z4.d, #0
	WORD $0x04b19410 // lsr z16.d, z0.d, #47
	WORD $0x04b03000 // eor z0.d, z0.d, z16.d
	WORD $0xa5e0a030 // ld1d {z16.d}, p0/z, [x1]
	WORD $0x04b03000 // eor z0.d, z0.d, z16.d
	WORD $0x04ef6000 // mul z0.d, z0.d, z15.d
	WORD $0xe5e0e000 // st1d {z0.d}, p0, [x0]
	RET
