/*
 * Emits ../rapidhash/vectors_test.go from the reference rapidhash, so the
 * results the Go implementation is measured against come from the C code
 * rather than from another port of it.
 *
 *   git clone --depth 1 https://github.com/Nicoshev/rapidhash
 *   cc -O2 -Irapidhash -o rapidgen rapidgen.c
 *   ./rapidgen > ../rapidhash/vectors_test.go
 *
 * The input buffer is filled the same way gen.c fills its own, so a length
 * here holds the same bytes as the same length there.
 *
 * The lengths cover every boundary the algorithm has -- 3/4, 7/8, 16/17,
 * each rung of the 17..112 ladder, 112/113, and the 224-byte block loop
 * either side of one and two iterations -- plus every length to 128, where
 * most of the branching lives.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "rapidhash.h"

#define PRIME32 2654435761U
#define PRIME64 11400714785074694797ULL

static void fillBuf(unsigned char *b, size_t len) {
    unsigned long long g = PRIME32;
    for (size_t i = 0; i < len; i++) { b[i] = (unsigned char)(g >> 56); g *= PRIME64; }
}

int main(void) {
    size_t lens[512];
    int nl = 0;
    for (size_t n = 0; n <= 128; n++) lens[nl++] = n;
    size_t extra[] = {
        129, 143, 144, 160, 176, 192, 208, 223, 224, 225, 239, 240,
        255, 256, 257, 335, 336, 337, 447, 448, 449, 511, 512, 513,
        1023, 1024, 1025, 4096, 8192, 10000, 65535, 65536, 65537, 1048576,
    };
    for (size_t i = 0; i < sizeof(extra)/sizeof(extra[0]); i++) lens[nl++] = extra[i];

    unsigned long long seeds[] = {
        0ULL, 1ULL, 0x9e3779b185ebca87ULL, 0xffffffffffffffffULL,
    };

    size_t max = 0;
    for (int i = 0; i < nl; i++) if (lens[i] > max) max = lens[i];
    unsigned char *buf = malloc(max ? max : 1);
    if (!buf) return 1;
    fillBuf(buf, max);

    printf("// Code generated by ref/rapidgen.c from the reference rapidhash. DO NOT EDIT.\n\n");
    printf("package rapidhash\n\n");
    printf("// refVec is one reference result: the rapidhash of the first Len bytes of\n");
    printf("// the canonical test buffer, under Seed.\n");
    printf("type refVec struct {\n\tLen  int\n\tSeed uint64\n\tH64  uint64\n}\n\n");
    printf("var refVecs = []refVec{\n");
    for (int li = 0; li < nl; li++) {
        for (unsigned si = 0; si < sizeof(seeds)/sizeof(seeds[0]); si++) {
            size_t len = lens[li];
            unsigned long long seed = seeds[si];
            /* The long tail only needs one seed each; the branching is all below 128. */
            if (si > 0 && len > 4200 && len != 65536 && len != 1048576) continue;
            unsigned long long h = rapidhash_withSeed(buf, len, seed);
            printf("\t{%zu, 0x%016llx, 0x%016llx},\n", len, seed, h);
        }
    }
    printf("}\n");
    free(buf);
    return 0;
}
