// Code generated by internal/asmgen. DO NOT EDIT.
//
// scalar kernels for arm64. Each line is one instruction: the
// bytes were produced by the system assembler from the generator's output,
// and the comment is the disassembly of exactly those bytes.

//go:build !purego

#include "textflag.h"

// func sum64Scalar(in unsafe.Pointer, n int, seed uint64) uint64
//
// hashes the n bytes at in under seed, whatever n is: lanes, merge, tail and avalanche in one call.
TEXT ·sum64Scalar(SB), NOSPLIT, $0-32
	MOVD in+0(FP), R0
	MOVD n+8(FP), R1
	MOVD seed+16(FP), R2
	MOVD $·primes(SB), R23
	WORD $0xa94016e4 // ldp x4, x5, [x23]
	WORD $0xa9411ee6 // ldp x6, x7, [x23, #16]
	WORD $0xf94012e8 // ldr x8, [x23, #32]
	WORD $0xf100803f // cmp x1, #0x20
	WORD $0x5400232b // b.lt 474 <kernel+0x474> // b.tstop
	WORD $0x8b04004a // add x10, x2, x4
	WORD $0x8b05014a // add x10, x10, x5
	WORD $0x8b05004b // add x11, x2, x5
	WORD $0xaa0203ec // mov x12, x2
	WORD $0xcb04004d // sub x13, x2, x4
	WORD $0xaa0103e2 // mov x2, x1
	WORD $0xd345fc42 // lsr x2, x2, #5
	WORD $0xf94016ee // ldr x14, [x23, #40]
	WORD $0xb400112e // cbz x14, 258 <kernel+0x258>
	WORD $0x36000282 // tbz w2, #0, 88 <kernel+0x88>
	WORD $0xa9403c0e // ldp x14, x15, [x0]
	WORD $0xa9414410 // ldp x16, x17, [x0, #16]
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x8b0e014a // add x10, x10, x14
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b057def // mul x15, x15, x5
	WORD $0x8b0f016b // add x11, x11, x15
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b057e10 // mul x16, x16, x5
	WORD $0x8b10018c // add x12, x12, x16
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b057e31 // mul x17, x17, x5
	WORD $0x8b1101ad // add x13, x13, x17
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0x91008000 // add x0, x0, #0x20
	// .Leven5:
	WORD $0x360804c2 // tbz w2, #1, 120 <kernel+0x120>
	WORD $0xa9403c0e // ldp x14, x15, [x0]
	WORD $0xa9414410 // ldp x16, x17, [x0, #16]
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x8b0e014a // add x10, x10, x14
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b057def // mul x15, x15, x5
	WORD $0x8b0f016b // add x11, x11, x15
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b057e10 // mul x16, x16, x5
	WORD $0x8b10018c // add x12, x12, x16
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b057e31 // mul x17, x17, x5
	WORD $0x8b1101ad // add x13, x13, x17
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xa9423c0e // ldp x14, x15, [x0, #32]
	WORD $0xa9434410 // ldp x16, x17, [x0, #48]
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x8b0e014a // add x10, x10, x14
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b057def // mul x15, x15, x5
	WORD $0x8b0f016b // add x11, x11, x15
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b057e10 // mul x16, x16, x5
	WORD $0x8b10018c // add x12, x12, x16
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b057e31 // mul x17, x17, x5
	WORD $0x8b1101ad // add x13, x13, x17
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0x91010000 // add x0, x0, #0x40
	// .Leven6:
	WORD $0xd342fc42 // lsr x2, x2, #2
	WORD $0xb4000982 // cbz x2, 254 <kernel+0x254>
	// .Lblocks7:
	WORD $0xa9403c0e // ldp x14, x15, [x0]
	WORD $0xa9414410 // ldp x16, x17, [x0, #16]
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x8b0e014a // add x10, x10, x14
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b057def // mul x15, x15, x5
	WORD $0x8b0f016b // add x11, x11, x15
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b057e10 // mul x16, x16, x5
	WORD $0x8b10018c // add x12, x12, x16
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b057e31 // mul x17, x17, x5
	WORD $0x8b1101ad // add x13, x13, x17
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xa9423c0e // ldp x14, x15, [x0, #32]
	WORD $0xa9434410 // ldp x16, x17, [x0, #48]
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x8b0e014a // add x10, x10, x14
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b057def // mul x15, x15, x5
	WORD $0x8b0f016b // add x11, x11, x15
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b057e10 // mul x16, x16, x5
	WORD $0x8b10018c // add x12, x12, x16
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b057e31 // mul x17, x17, x5
	WORD $0x8b1101ad // add x13, x13, x17
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xa9443c0e // ldp x14, x15, [x0, #64]
	WORD $0xa9454410 // ldp x16, x17, [x0, #80]
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x8b0e014a // add x10, x10, x14
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b057def // mul x15, x15, x5
	WORD $0x8b0f016b // add x11, x11, x15
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b057e10 // mul x16, x16, x5
	WORD $0x8b10018c // add x12, x12, x16
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b057e31 // mul x17, x17, x5
	WORD $0x8b1101ad // add x13, x13, x17
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xa9463c0e // ldp x14, x15, [x0, #96]
	WORD $0xa9474410 // ldp x16, x17, [x0, #112]
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x8b0e014a // add x10, x10, x14
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b057def // mul x15, x15, x5
	WORD $0x8b0f016b // add x11, x11, x15
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b057e10 // mul x16, x16, x5
	WORD $0x8b10018c // add x12, x12, x16
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b057e31 // mul x17, x17, x5
	WORD $0x8b1101ad // add x13, x13, x17
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0x91020000 // add x0, x0, #0x80
	WORD $0xf1000442 // subs x2, x2, #0x1
	WORD $0x54fff6c1 // b.ne 128 <kernel+0x128> // b.any
	// .Lbdone8:
	WORD $0x1400006c // b 404 <kernel+0x404>
	// .Lfused3:
	WORD $0x36000202 // tbz w2, #0, 298 <kernel+0x298>
	WORD $0xa9403c0e // ldp x14, x15, [x0]
	WORD $0xa9414410 // ldp x16, x17, [x0, #16]
	WORD $0x9b0529ca // madd x10, x14, x5, x10
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b052deb // madd x11, x15, x5, x11
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b05320c // madd x12, x16, x5, x12
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b05362d // madd x13, x17, x5, x13
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0x91008000 // add x0, x0, #0x20
	// .Leven9:
	WORD $0x360803c2 // tbz w2, #1, 310 <kernel+0x310>
	WORD $0xa9403c0e // ldp x14, x15, [x0]
	WORD $0xa9414410 // ldp x16, x17, [x0, #16]
	WORD $0x9b0529ca // madd x10, x14, x5, x10
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b052deb // madd x11, x15, x5, x11
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b05320c // madd x12, x16, x5, x12
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b05362d // madd x13, x17, x5, x13
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xa9423c0e // ldp x14, x15, [x0, #32]
	WORD $0xa9434410 // ldp x16, x17, [x0, #48]
	WORD $0x9b0529ca // madd x10, x14, x5, x10
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b052deb // madd x11, x15, x5, x11
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b05320c // madd x12, x16, x5, x12
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b05362d // madd x13, x17, x5, x13
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0x91010000 // add x0, x0, #0x40
	// .Leven10:
	WORD $0xd342fc42 // lsr x2, x2, #2
	WORD $0xb4000782 // cbz x2, 404 <kernel+0x404>
	// .Lblocks11:
	WORD $0xa9403c0e // ldp x14, x15, [x0]
	WORD $0xa9414410 // ldp x16, x17, [x0, #16]
	WORD $0x9b0529ca // madd x10, x14, x5, x10
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b052deb // madd x11, x15, x5, x11
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b05320c // madd x12, x16, x5, x12
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b05362d // madd x13, x17, x5, x13
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xa9423c0e // ldp x14, x15, [x0, #32]
	WORD $0xa9434410 // ldp x16, x17, [x0, #48]
	WORD $0x9b0529ca // madd x10, x14, x5, x10
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b052deb // madd x11, x15, x5, x11
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b05320c // madd x12, x16, x5, x12
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b05362d // madd x13, x17, x5, x13
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xa9443c0e // ldp x14, x15, [x0, #64]
	WORD $0xa9454410 // ldp x16, x17, [x0, #80]
	WORD $0x9b0529ca // madd x10, x14, x5, x10
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b052deb // madd x11, x15, x5, x11
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b05320c // madd x12, x16, x5, x12
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b05362d // madd x13, x17, x5, x13
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xa9463c0e // ldp x14, x15, [x0, #96]
	WORD $0xa9474410 // ldp x16, x17, [x0, #112]
	WORD $0x9b0529ca // madd x10, x14, x5, x10
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b052deb // madd x11, x15, x5, x11
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b05320c // madd x12, x16, x5, x12
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b05362d // madd x13, x17, x5, x13
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0x91020000 // add x0, x0, #0x80
	WORD $0xf1000442 // subs x2, x2, #0x1
	WORD $0x54fff8c1 // b.ne 318 <kernel+0x318> // b.any
	// .Lbdone12:
	// .Ljoin4:
	WORD $0x93cafd49 // ror x9, x10, #63
	WORD $0x93cbe573 // ror x19, x11, #57
	WORD $0x8b130129 // add x9, x9, x19
	WORD $0x93ccd193 // ror x19, x12, #52
	WORD $0x93cdb9a2 // ror x2, x13, #46
	WORD $0x8b020273 // add x19, x19, x2
	WORD $0x8b130129 // add x9, x9, x19
	WORD $0x9b057d4a // mul x10, x10, x5
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0xca0a0129 // eor x9, x9, x10
	WORD $0x9b041d29 // madd x9, x9, x4, x7
	WORD $0x9b057d6b // mul x11, x11, x5
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0xca0b0129 // eor x9, x9, x11
	WORD $0x9b041d29 // madd x9, x9, x4, x7
	WORD $0x9b057d8c // mul x12, x12, x5
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0xca0c0129 // eor x9, x9, x12
	WORD $0x9b041d29 // madd x9, x9, x4, x7
	WORD $0x9b057dad // mul x13, x13, x5
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xca0d0129 // eor x9, x9, x13
	WORD $0x9b041d29 // madd x9, x9, x4, x7
	WORD $0x14000003 // b 47c <kernel+0x47c>
	// .Lshort1:
	WORD $0xaa0203e9 // mov x9, x2
	WORD $0x8b080129 // add x9, x9, x8
	// .Ltail2:
	WORD $0x8b010129 // add x9, x9, x1
	WORD $0x362001e1 // tbz w1, #4, 4bc <kernel+0x4bc>
	WORD $0xf840840e // ldr x14, [x0], #8
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x93ce85ce // ror x14, x14, #33
	WORD $0x9b047dce // mul x14, x14, x4
	WORD $0xca0e0129 // eor x9, x9, x14
	WORD $0x93c99529 // ror x9, x9, #37
	WORD $0x9b041d29 // madd x9, x9, x4, x7
	WORD $0xf840840e // ldr x14, [x0], #8
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x93ce85ce // ror x14, x14, #33
	WORD $0x9b047dce // mul x14, x14, x4
	WORD $0xca0e0129 // eor x9, x9, x14
	WORD $0x93c99529 // ror x9, x9, #37
	WORD $0x9b041d29 // madd x9, x9, x4, x7
	// .Lt813:
	WORD $0x36180101 // tbz w1, #3, 4dc <kernel+0x4dc>
	WORD $0xf840840e // ldr x14, [x0], #8
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x93ce85ce // ror x14, x14, #33
	WORD $0x9b047dce // mul x14, x14, x4
	WORD $0xca0e0129 // eor x9, x9, x14
	WORD $0x93c99529 // ror x9, x9, #37
	WORD $0x9b041d29 // madd x9, x9, x4, x7
	// .Lt414:
	WORD $0x361000c1 // tbz w1, #2, 4f4 <kernel+0x4f4>
	WORD $0xb840440e // ldr w14, [x0], #4
	WORD $0x9b047dce // mul x14, x14, x4
	WORD $0xca0e0129 // eor x9, x9, x14
	WORD $0x93c9a529 // ror x9, x9, #41
	WORD $0x9b051929 // madd x9, x9, x5, x6
	// .Lt215:
	WORD $0x36080161 // tbz w1, #1, 520 <kernel+0x520>
	WORD $0x3840140e // ldrb w14, [x0], #1
	WORD $0x9b087dce // mul x14, x14, x8
	WORD $0xca0e0129 // eor x9, x9, x14
	WORD $0x93c9d529 // ror x9, x9, #53
	WORD $0x9b047d29 // mul x9, x9, x4
	WORD $0x3840140e // ldrb w14, [x0], #1
	WORD $0x9b087dce // mul x14, x14, x8
	WORD $0xca0e0129 // eor x9, x9, x14
	WORD $0x93c9d529 // ror x9, x9, #53
	WORD $0x9b047d29 // mul x9, x9, x4
	// .Lt116:
	WORD $0x360000c1 // tbz w1, #0, 538 <kernel+0x538>
	WORD $0x3840140e // ldrb w14, [x0], #1
	WORD $0x9b087dce // mul x14, x14, x8
	WORD $0xca0e0129 // eor x9, x9, x14
	WORD $0x93c9d529 // ror x9, x9, #53
	WORD $0x9b047d29 // mul x9, x9, x4
	// .Lfin17:
	WORD $0xca498529 // eor x9, x9, x9, lsr #33
	WORD $0x9b057d29 // mul x9, x9, x5
	WORD $0xca497529 // eor x9, x9, x9, lsr #29
	WORD $0x9b067d29 // mul x9, x9, x6
	WORD $0xca498129 // eor x9, x9, x9, lsr #32
	MOVD R9, ret+24(FP)
	RET

// func blocksScalar(lanes *[4]uint64, in unsafe.Pointer, nbBlocks int)
//
// absorbs nbBlocks whole blocks at in into the four lanes.
TEXT ·blocksScalar(SB), NOSPLIT, $0-24
	MOVD lanes+0(FP), R0
	MOVD in+8(FP), R1
	MOVD nbBlocks+16(FP), R2
	MOVD $·primes(SB), R23
	WORD $0xa94016e4 // ldp x4, x5, [x23]
	WORD $0xa9411ee6 // ldp x6, x7, [x23, #16]
	WORD $0xf94012e8 // ldr x8, [x23, #32]
	WORD $0xa9402c0a // ldp x10, x11, [x0]
	WORD $0xa941340c // ldp x12, x13, [x0, #16]
	WORD $0xf94016ee // ldr x14, [x23, #40]
	WORD $0xb400112e // cbz x14, 23c <kernel+0x23c>
	WORD $0x36000282 // tbz w2, #0, 6c <kernel+0x6c>
	WORD $0xa9403c2e // ldp x14, x15, [x1]
	WORD $0xa9414430 // ldp x16, x17, [x1, #16]
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x8b0e014a // add x10, x10, x14
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b057def // mul x15, x15, x5
	WORD $0x8b0f016b // add x11, x11, x15
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b057e10 // mul x16, x16, x5
	WORD $0x8b10018c // add x12, x12, x16
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b057e31 // mul x17, x17, x5
	WORD $0x8b1101ad // add x13, x13, x17
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0x91008021 // add x1, x1, #0x20
	// .Leven3:
	WORD $0x360804c2 // tbz w2, #1, 104 <kernel+0x104>
	WORD $0xa9403c2e // ldp x14, x15, [x1]
	WORD $0xa9414430 // ldp x16, x17, [x1, #16]
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x8b0e014a // add x10, x10, x14
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b057def // mul x15, x15, x5
	WORD $0x8b0f016b // add x11, x11, x15
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b057e10 // mul x16, x16, x5
	WORD $0x8b10018c // add x12, x12, x16
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b057e31 // mul x17, x17, x5
	WORD $0x8b1101ad // add x13, x13, x17
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xa9423c2e // ldp x14, x15, [x1, #32]
	WORD $0xa9434430 // ldp x16, x17, [x1, #48]
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x8b0e014a // add x10, x10, x14
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b057def // mul x15, x15, x5
	WORD $0x8b0f016b // add x11, x11, x15
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b057e10 // mul x16, x16, x5
	WORD $0x8b10018c // add x12, x12, x16
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b057e31 // mul x17, x17, x5
	WORD $0x8b1101ad // add x13, x13, x17
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0x91010021 // add x1, x1, #0x40
	// .Leven4:
	WORD $0xd342fc42 // lsr x2, x2, #2
	WORD $0xb4000982 // cbz x2, 238 <kernel+0x238>
	// .Lblocks5:
	WORD $0xa9403c2e // ldp x14, x15, [x1]
	WORD $0xa9414430 // ldp x16, x17, [x1, #16]
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x8b0e014a // add x10, x10, x14
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b057def // mul x15, x15, x5
	WORD $0x8b0f016b // add x11, x11, x15
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b057e10 // mul x16, x16, x5
	WORD $0x8b10018c // add x12, x12, x16
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b057e31 // mul x17, x17, x5
	WORD $0x8b1101ad // add x13, x13, x17
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xa9423c2e // ldp x14, x15, [x1, #32]
	WORD $0xa9434430 // ldp x16, x17, [x1, #48]
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x8b0e014a // add x10, x10, x14
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b057def // mul x15, x15, x5
	WORD $0x8b0f016b // add x11, x11, x15
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b057e10 // mul x16, x16, x5
	WORD $0x8b10018c // add x12, x12, x16
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b057e31 // mul x17, x17, x5
	WORD $0x8b1101ad // add x13, x13, x17
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xa9443c2e // ldp x14, x15, [x1, #64]
	WORD $0xa9454430 // ldp x16, x17, [x1, #80]
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x8b0e014a // add x10, x10, x14
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b057def // mul x15, x15, x5
	WORD $0x8b0f016b // add x11, x11, x15
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b057e10 // mul x16, x16, x5
	WORD $0x8b10018c // add x12, x12, x16
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b057e31 // mul x17, x17, x5
	WORD $0x8b1101ad // add x13, x13, x17
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xa9463c2e // ldp x14, x15, [x1, #96]
	WORD $0xa9474430 // ldp x16, x17, [x1, #112]
	WORD $0x9b057dce // mul x14, x14, x5
	WORD $0x8b0e014a // add x10, x10, x14
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b057def // mul x15, x15, x5
	WORD $0x8b0f016b // add x11, x11, x15
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b057e10 // mul x16, x16, x5
	WORD $0x8b10018c // add x12, x12, x16
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b057e31 // mul x17, x17, x5
	WORD $0x8b1101ad // add x13, x13, x17
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0x91020021 // add x1, x1, #0x80
	WORD $0xf1000442 // subs x2, x2, #0x1
	WORD $0x54fff6c1 // b.ne 10c <kernel+0x10c> // b.any
	// .Lbdone6:
	WORD $0x1400006c // b 3e8 <kernel+0x3e8>
	// .Lfused1:
	WORD $0x36000202 // tbz w2, #0, 27c <kernel+0x27c>
	WORD $0xa9403c2e // ldp x14, x15, [x1]
	WORD $0xa9414430 // ldp x16, x17, [x1, #16]
	WORD $0x9b0529ca // madd x10, x14, x5, x10
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b052deb // madd x11, x15, x5, x11
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b05320c // madd x12, x16, x5, x12
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b05362d // madd x13, x17, x5, x13
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0x91008021 // add x1, x1, #0x20
	// .Leven7:
	WORD $0x360803c2 // tbz w2, #1, 2f4 <kernel+0x2f4>
	WORD $0xa9403c2e // ldp x14, x15, [x1]
	WORD $0xa9414430 // ldp x16, x17, [x1, #16]
	WORD $0x9b0529ca // madd x10, x14, x5, x10
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b052deb // madd x11, x15, x5, x11
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b05320c // madd x12, x16, x5, x12
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b05362d // madd x13, x17, x5, x13
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xa9423c2e // ldp x14, x15, [x1, #32]
	WORD $0xa9434430 // ldp x16, x17, [x1, #48]
	WORD $0x9b0529ca // madd x10, x14, x5, x10
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b052deb // madd x11, x15, x5, x11
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b05320c // madd x12, x16, x5, x12
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b05362d // madd x13, x17, x5, x13
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0x91010021 // add x1, x1, #0x40
	// .Leven8:
	WORD $0xd342fc42 // lsr x2, x2, #2
	WORD $0xb4000782 // cbz x2, 3e8 <kernel+0x3e8>
	// .Lblocks9:
	WORD $0xa9403c2e // ldp x14, x15, [x1]
	WORD $0xa9414430 // ldp x16, x17, [x1, #16]
	WORD $0x9b0529ca // madd x10, x14, x5, x10
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b052deb // madd x11, x15, x5, x11
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b05320c // madd x12, x16, x5, x12
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b05362d // madd x13, x17, x5, x13
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xa9423c2e // ldp x14, x15, [x1, #32]
	WORD $0xa9434430 // ldp x16, x17, [x1, #48]
	WORD $0x9b0529ca // madd x10, x14, x5, x10
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b052deb // madd x11, x15, x5, x11
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b05320c // madd x12, x16, x5, x12
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b05362d // madd x13, x17, x5, x13
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xa9443c2e // ldp x14, x15, [x1, #64]
	WORD $0xa9454430 // ldp x16, x17, [x1, #80]
	WORD $0x9b0529ca // madd x10, x14, x5, x10
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b052deb // madd x11, x15, x5, x11
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b05320c // madd x12, x16, x5, x12
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b05362d // madd x13, x17, x5, x13
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0xa9463c2e // ldp x14, x15, [x1, #96]
	WORD $0xa9474430 // ldp x16, x17, [x1, #112]
	WORD $0x9b0529ca // madd x10, x14, x5, x10
	WORD $0x93ca854a // ror x10, x10, #33
	WORD $0x9b047d4a // mul x10, x10, x4
	WORD $0x9b052deb // madd x11, x15, x5, x11
	WORD $0x93cb856b // ror x11, x11, #33
	WORD $0x9b047d6b // mul x11, x11, x4
	WORD $0x9b05320c // madd x12, x16, x5, x12
	WORD $0x93cc858c // ror x12, x12, #33
	WORD $0x9b047d8c // mul x12, x12, x4
	WORD $0x9b05362d // madd x13, x17, x5, x13
	WORD $0x93cd85ad // ror x13, x13, #33
	WORD $0x9b047dad // mul x13, x13, x4
	WORD $0x91020021 // add x1, x1, #0x80
	WORD $0xf1000442 // subs x2, x2, #0x1
	WORD $0x54fff8c1 // b.ne 2fc <kernel+0x2fc> // b.any
	// .Lbdone10:
	// .Ljoin2:
	WORD $0xf900000a // str x10, [x0]
	WORD $0xf900040b // str x11, [x0, #8]
	WORD $0xf900080c // str x12, [x0, #16]
	WORD $0xf9000c0d // str x13, [x0, #24]
	RET
