// Code generated by internal/asmgen. DO NOT EDIT.
//
// scalar kernels for arm64. Each line is one instruction: the
// bytes were produced by the system assembler from the generator's output,
// and the comment is the disassembly of exactly those bytes.

//go:build !purego

#include "textflag.h"

// func sum64Rapid(in unsafe.Pointer, n int, seed uint64) uint64
//
// hashes the n bytes at in under seed, whatever n is: every length class and the fold in one call.
TEXT ·sum64Rapid(SB), NOSPLIT, $0-32
	MOVD in+0(FP), R0
	MOVD n+8(FP), R1
	MOVD seed+16(FP), R2
	MOVD $·secret(SB), R3
	WORD $0xf940086c // ldr x12, [x3, #16]
	WORD $0xca02018c // eor x12, x12, x2
	WORD $0xf940046a // ldr x10, [x3, #8]
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0x9b0a7d8c // mul x12, x12, x10
	WORD $0xca0d018c // eor x12, x12, x13
	WORD $0xca0c0042 // eor x2, x2, x12
	WORD $0xf100403f // cmp x1, #0x10
	WORD $0x540003cc // b.gt 98 <kernel+0x98>
	// .Lshort1:
	WORD $0xf100103f // cmp x1, #0x4
	WORD $0x540001cb // b.lt 60 <kernel+0x60> // b.tstop
	WORD $0xca010042 // eor x2, x2, x1
	WORD $0xf100203f // cmp x1, #0x8
	WORD $0x540000ca // b.ge 4c <kernel+0x4c> // b.tcont
	WORD $0xb940000a // ldr w10, [x0]
	WORD $0xaa0103ec // mov x12, x1
	WORD $0xd100118c // sub x12, x12, #0x4
	WORD $0xb86c680b // ldr w11, [x0, x12]
	WORD $0x14000005 // b 5c <kernel+0x5c>
	// .Leight7:
	WORD $0xf940000a // ldr x10, [x0]
	WORD $0xaa0103ec // mov x12, x1
	WORD $0xd100218c // sub x12, x12, #0x8
	WORD $0xf86c680b // ldr x11, [x0, x12]
	// .Lshortdone8:
	WORD $0x140000dd // b 3d0 <kernel+0x3d0>
	// .Lshort1to32:
	WORD $0xf100003f // cmp x1, #0x0
	WORD $0x54000140 // b.eq 8c <kernel+0x8c> // b.none
	WORD $0x3940000a // ldrb w10, [x0]
	WORD $0xd353494a // lsl x10, x10, #45
	WORD $0xaa0103ec // mov x12, x1
	WORD $0xd100058c // sub x12, x12, #0x1
	WORD $0x386c680b // ldrb w11, [x0, x12]
	WORD $0xaa0b014a // orr x10, x10, x11
	WORD $0xd341fc2c // lsr x12, x1, #1
	WORD $0x386c680b // ldrb w11, [x0, x12]
	WORD $0x140000d2 // b 3d0 <kernel+0x3d0>
	// .Lempty3:
	WORD $0xaa1f03ea // mov x10, xzr
	WORD $0xaa1f03eb // mov x11, xzr
	WORD $0x140000cf // b 3d0 <kernel+0x3d0>
	// .Lblocks6:
	WORD $0xa940c06f // ldp x15, x16, [x3, #8]
	WORD $0xf101c03f // cmp x1, #0x70
	WORD $0x5400130d // b.le 300 <kernel+0x300>
	WORD $0xaa0203e4 // mov x4, x2
	WORD $0xaa0203e5 // mov x5, x2
	WORD $0xaa0203e6 // mov x6, x2
	WORD $0xaa0203e7 // mov x7, x2
	WORD $0xaa0203e8 // mov x8, x2
	WORD $0xaa0203e9 // mov x9, x2
	WORD $0xf940006e // ldr x14, [x3]
	WORD $0xa941cc71 // ldp x17, x19, [x3, #24]
	WORD $0xa942d474 // ldp x20, x21, [x3, #40]
	WORD $0xf103803f // cmp x1, #0xe0
	WORD $0x54000b2d // b.le 230 <kernel+0x230>
	// .Lloop9:
	WORD $0xa940280c // ldp x12, x10, [x0]
	WORD $0xca0e018c // eor x12, x12, x14
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	WORD $0xa941280c // ldp x12, x10, [x0, #16]
	WORD $0xca0f018c // eor x12, x12, x15
	WORD $0xca04014a // eor x10, x10, x4
	WORD $0x9b0a7d84 // mul x4, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0084 // eor x4, x4, x13
	WORD $0xa942280c // ldp x12, x10, [x0, #32]
	WORD $0xca10018c // eor x12, x12, x16
	WORD $0xca05014a // eor x10, x10, x5
	WORD $0x9b0a7d85 // mul x5, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00a5 // eor x5, x5, x13
	WORD $0xa943280c // ldp x12, x10, [x0, #48]
	WORD $0xca11018c // eor x12, x12, x17
	WORD $0xca06014a // eor x10, x10, x6
	WORD $0x9b0a7d86 // mul x6, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00c6 // eor x6, x6, x13
	WORD $0xa944280c // ldp x12, x10, [x0, #64]
	WORD $0xca13018c // eor x12, x12, x19
	WORD $0xca07014a // eor x10, x10, x7
	WORD $0x9b0a7d87 // mul x7, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00e7 // eor x7, x7, x13
	WORD $0xa945280c // ldp x12, x10, [x0, #80]
	WORD $0xca14018c // eor x12, x12, x20
	WORD $0xca08014a // eor x10, x10, x8
	WORD $0x9b0a7d88 // mul x8, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0108 // eor x8, x8, x13
	WORD $0xa946280c // ldp x12, x10, [x0, #96]
	WORD $0xca15018c // eor x12, x12, x21
	WORD $0xca09014a // eor x10, x10, x9
	WORD $0x9b0a7d89 // mul x9, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0129 // eor x9, x9, x13
	WORD $0xa947280c // ldp x12, x10, [x0, #112]
	WORD $0xca0e018c // eor x12, x12, x14
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	WORD $0xa948280c // ldp x12, x10, [x0, #128]
	WORD $0xca0f018c // eor x12, x12, x15
	WORD $0xca04014a // eor x10, x10, x4
	WORD $0x9b0a7d84 // mul x4, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0084 // eor x4, x4, x13
	WORD $0xa949280c // ldp x12, x10, [x0, #144]
	WORD $0xca10018c // eor x12, x12, x16
	WORD $0xca05014a // eor x10, x10, x5
	WORD $0x9b0a7d85 // mul x5, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00a5 // eor x5, x5, x13
	WORD $0xa94a280c // ldp x12, x10, [x0, #160]
	WORD $0xca11018c // eor x12, x12, x17
	WORD $0xca06014a // eor x10, x10, x6
	WORD $0x9b0a7d86 // mul x6, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00c6 // eor x6, x6, x13
	WORD $0xa94b280c // ldp x12, x10, [x0, #176]
	WORD $0xca13018c // eor x12, x12, x19
	WORD $0xca07014a // eor x10, x10, x7
	WORD $0x9b0a7d87 // mul x7, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00e7 // eor x7, x7, x13
	WORD $0xa94c280c // ldp x12, x10, [x0, #192]
	WORD $0xca14018c // eor x12, x12, x20
	WORD $0xca08014a // eor x10, x10, x8
	WORD $0x9b0a7d88 // mul x8, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0108 // eor x8, x8, x13
	WORD $0xa94d280c // ldp x12, x10, [x0, #208]
	WORD $0xca15018c // eor x12, x12, x21
	WORD $0xca09014a // eor x10, x10, x9
	WORD $0x9b0a7d89 // mul x9, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0129 // eor x9, x9, x13
	WORD $0x91038000 // add x0, x0, #0xe0
	WORD $0xd1038021 // sub x1, x1, #0xe0
	WORD $0xf103803f // cmp x1, #0xe0
	WORD $0x54fff52c // b.gt d0 <kernel+0xd0>
	// .Lone10:
	WORD $0xf101c03f // cmp x1, #0x70
	WORD $0x540005ad // b.le 2e8 <kernel+0x2e8>
	WORD $0xa940280c // ldp x12, x10, [x0]
	WORD $0xca0e018c // eor x12, x12, x14
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	WORD $0xa941280c // ldp x12, x10, [x0, #16]
	WORD $0xca0f018c // eor x12, x12, x15
	WORD $0xca04014a // eor x10, x10, x4
	WORD $0x9b0a7d84 // mul x4, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0084 // eor x4, x4, x13
	WORD $0xa942280c // ldp x12, x10, [x0, #32]
	WORD $0xca10018c // eor x12, x12, x16
	WORD $0xca05014a // eor x10, x10, x5
	WORD $0x9b0a7d85 // mul x5, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00a5 // eor x5, x5, x13
	WORD $0xa943280c // ldp x12, x10, [x0, #48]
	WORD $0xca11018c // eor x12, x12, x17
	WORD $0xca06014a // eor x10, x10, x6
	WORD $0x9b0a7d86 // mul x6, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00c6 // eor x6, x6, x13
	WORD $0xa944280c // ldp x12, x10, [x0, #64]
	WORD $0xca13018c // eor x12, x12, x19
	WORD $0xca07014a // eor x10, x10, x7
	WORD $0x9b0a7d87 // mul x7, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00e7 // eor x7, x7, x13
	WORD $0xa945280c // ldp x12, x10, [x0, #80]
	WORD $0xca14018c // eor x12, x12, x20
	WORD $0xca08014a // eor x10, x10, x8
	WORD $0x9b0a7d88 // mul x8, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0108 // eor x8, x8, x13
	WORD $0xa946280c // ldp x12, x10, [x0, #96]
	WORD $0xca15018c // eor x12, x12, x21
	WORD $0xca09014a // eor x10, x10, x9
	WORD $0x9b0a7d89 // mul x9, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0129 // eor x9, x9, x13
	WORD $0x9101c000 // add x0, x0, #0x70
	WORD $0xd101c021 // sub x1, x1, #0x70
	// .Lafter11:
	WORD $0xca040042 // eor x2, x2, x4
	WORD $0xca0600a5 // eor x5, x5, x6
	WORD $0xca0800e7 // eor x7, x7, x8
	WORD $0xca090042 // eor x2, x2, x9
	WORD $0xca0700a5 // eor x5, x5, x7
	WORD $0xca050042 // eor x2, x2, x5
	// .Ltail4:
	WORD $0xf100403f // cmp x1, #0x10
	WORD $0x540005ed // b.le 3c0 <kernel+0x3c0>
	WORD $0xa940280c // ldp x12, x10, [x0]
	WORD $0xca10018c // eor x12, x12, x16
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	WORD $0xf100803f // cmp x1, #0x20
	WORD $0x540004ed // b.le 3c0 <kernel+0x3c0>
	WORD $0xa941280c // ldp x12, x10, [x0, #16]
	WORD $0xca10018c // eor x12, x12, x16
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	WORD $0xf100c03f // cmp x1, #0x30
	WORD $0x540003ed // b.le 3c0 <kernel+0x3c0>
	WORD $0xa942280c // ldp x12, x10, [x0, #32]
	WORD $0xca0f018c // eor x12, x12, x15
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	WORD $0xf101003f // cmp x1, #0x40
	WORD $0x540002ed // b.le 3c0 <kernel+0x3c0>
	WORD $0xa943280c // ldp x12, x10, [x0, #48]
	WORD $0xca0f018c // eor x12, x12, x15
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	WORD $0xf101403f // cmp x1, #0x50
	WORD $0x540001ed // b.le 3c0 <kernel+0x3c0>
	WORD $0xa944280c // ldp x12, x10, [x0, #64]
	WORD $0xca10018c // eor x12, x12, x16
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	WORD $0xf101803f // cmp x1, #0x60
	WORD $0x540000ed // b.le 3c0 <kernel+0x3c0>
	WORD $0xa945280c // ldp x12, x10, [x0, #80]
	WORD $0xca0f018c // eor x12, x12, x15
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	// .Ltail1612:
	WORD $0x8b01000c // add x12, x0, x1
	WORD $0xf85f018a // ldur x10, [x12, #-16]
	WORD $0xf85f818b // ldur x11, [x12, #-8]
	WORD $0xca01014a // eor x10, x10, x1
	// .Ldone5:
	WORD $0xf940046c // ldr x12, [x3, #8]
	WORD $0xca0c014a // eor x10, x10, x12
	WORD $0xca02016b // eor x11, x11, x2
	WORD $0x9bcb7d45 // umulh x5, x10, x11
	WORD $0x9b0b7d44 // mul x4, x10, x11
	WORD $0xf9401c6a // ldr x10, [x3, #56]
	WORD $0xca0a0084 // eor x4, x4, x10
	WORD $0xca0c00a5 // eor x5, x5, x12
	WORD $0xca0100a5 // eor x5, x5, x1
	WORD $0x9b057c80 // mul x0, x4, x5
	WORD $0x9bc57c8d // umulh x13, x4, x5
	WORD $0xca0d0000 // eor x0, x0, x13
	MOVD R0, ret+24(FP)
	RET

// func sum64RapidNS(in unsafe.Pointer, n int) uint64
//
// is sum64Rapid with no seed: the prologue's mix is a constant, loaded rather than computed.
TEXT ·sum64RapidNS(SB), NOSPLIT, $0-24
	MOVD in+0(FP), R0
	MOVD n+8(FP), R1
	MOVD $·secret(SB), R3
	WORD $0xf9402062 // ldr x2, [x3, #64]
	WORD $0xf100403f // cmp x1, #0x10
	WORD $0x540003cc // b.gt 80 <kernel+0x80>
	// .Lshort1:
	WORD $0xf100103f // cmp x1, #0x4
	WORD $0x540001cb // b.lt 48 <kernel+0x48> // b.tstop
	WORD $0xca010042 // eor x2, x2, x1
	WORD $0xf100203f // cmp x1, #0x8
	WORD $0x540000ca // b.ge 34 <kernel+0x34> // b.tcont
	WORD $0xb940000a // ldr w10, [x0]
	WORD $0xaa0103ec // mov x12, x1
	WORD $0xd100118c // sub x12, x12, #0x4
	WORD $0xb86c680b // ldr w11, [x0, x12]
	WORD $0x14000005 // b 44 <kernel+0x44>
	// .Leight7:
	WORD $0xf940000a // ldr x10, [x0]
	WORD $0xaa0103ec // mov x12, x1
	WORD $0xd100218c // sub x12, x12, #0x8
	WORD $0xf86c680b // ldr x11, [x0, x12]
	// .Lshortdone8:
	WORD $0x140000dd // b 3b8 <kernel+0x3b8>
	// .Lshort1to32:
	WORD $0xf100003f // cmp x1, #0x0
	WORD $0x54000140 // b.eq 74 <kernel+0x74> // b.none
	WORD $0x3940000a // ldrb w10, [x0]
	WORD $0xd353494a // lsl x10, x10, #45
	WORD $0xaa0103ec // mov x12, x1
	WORD $0xd100058c // sub x12, x12, #0x1
	WORD $0x386c680b // ldrb w11, [x0, x12]
	WORD $0xaa0b014a // orr x10, x10, x11
	WORD $0xd341fc2c // lsr x12, x1, #1
	WORD $0x386c680b // ldrb w11, [x0, x12]
	WORD $0x140000d2 // b 3b8 <kernel+0x3b8>
	// .Lempty3:
	WORD $0xaa1f03ea // mov x10, xzr
	WORD $0xaa1f03eb // mov x11, xzr
	WORD $0x140000cf // b 3b8 <kernel+0x3b8>
	// .Lblocks6:
	WORD $0xa940c06f // ldp x15, x16, [x3, #8]
	WORD $0xf101c03f // cmp x1, #0x70
	WORD $0x5400130d // b.le 2e8 <kernel+0x2e8>
	WORD $0xaa0203e4 // mov x4, x2
	WORD $0xaa0203e5 // mov x5, x2
	WORD $0xaa0203e6 // mov x6, x2
	WORD $0xaa0203e7 // mov x7, x2
	WORD $0xaa0203e8 // mov x8, x2
	WORD $0xaa0203e9 // mov x9, x2
	WORD $0xf940006e // ldr x14, [x3]
	WORD $0xa941cc71 // ldp x17, x19, [x3, #24]
	WORD $0xa942d474 // ldp x20, x21, [x3, #40]
	WORD $0xf103803f // cmp x1, #0xe0
	WORD $0x54000b2d // b.le 218 <kernel+0x218>
	// .Lloop9:
	WORD $0xa940280c // ldp x12, x10, [x0]
	WORD $0xca0e018c // eor x12, x12, x14
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	WORD $0xa941280c // ldp x12, x10, [x0, #16]
	WORD $0xca0f018c // eor x12, x12, x15
	WORD $0xca04014a // eor x10, x10, x4
	WORD $0x9b0a7d84 // mul x4, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0084 // eor x4, x4, x13
	WORD $0xa942280c // ldp x12, x10, [x0, #32]
	WORD $0xca10018c // eor x12, x12, x16
	WORD $0xca05014a // eor x10, x10, x5
	WORD $0x9b0a7d85 // mul x5, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00a5 // eor x5, x5, x13
	WORD $0xa943280c // ldp x12, x10, [x0, #48]
	WORD $0xca11018c // eor x12, x12, x17
	WORD $0xca06014a // eor x10, x10, x6
	WORD $0x9b0a7d86 // mul x6, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00c6 // eor x6, x6, x13
	WORD $0xa944280c // ldp x12, x10, [x0, #64]
	WORD $0xca13018c // eor x12, x12, x19
	WORD $0xca07014a // eor x10, x10, x7
	WORD $0x9b0a7d87 // mul x7, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00e7 // eor x7, x7, x13
	WORD $0xa945280c // ldp x12, x10, [x0, #80]
	WORD $0xca14018c // eor x12, x12, x20
	WORD $0xca08014a // eor x10, x10, x8
	WORD $0x9b0a7d88 // mul x8, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0108 // eor x8, x8, x13
	WORD $0xa946280c // ldp x12, x10, [x0, #96]
	WORD $0xca15018c // eor x12, x12, x21
	WORD $0xca09014a // eor x10, x10, x9
	WORD $0x9b0a7d89 // mul x9, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0129 // eor x9, x9, x13
	WORD $0xa947280c // ldp x12, x10, [x0, #112]
	WORD $0xca0e018c // eor x12, x12, x14
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	WORD $0xa948280c // ldp x12, x10, [x0, #128]
	WORD $0xca0f018c // eor x12, x12, x15
	WORD $0xca04014a // eor x10, x10, x4
	WORD $0x9b0a7d84 // mul x4, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0084 // eor x4, x4, x13
	WORD $0xa949280c // ldp x12, x10, [x0, #144]
	WORD $0xca10018c // eor x12, x12, x16
	WORD $0xca05014a // eor x10, x10, x5
	WORD $0x9b0a7d85 // mul x5, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00a5 // eor x5, x5, x13
	WORD $0xa94a280c // ldp x12, x10, [x0, #160]
	WORD $0xca11018c // eor x12, x12, x17
	WORD $0xca06014a // eor x10, x10, x6
	WORD $0x9b0a7d86 // mul x6, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00c6 // eor x6, x6, x13
	WORD $0xa94b280c // ldp x12, x10, [x0, #176]
	WORD $0xca13018c // eor x12, x12, x19
	WORD $0xca07014a // eor x10, x10, x7
	WORD $0x9b0a7d87 // mul x7, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00e7 // eor x7, x7, x13
	WORD $0xa94c280c // ldp x12, x10, [x0, #192]
	WORD $0xca14018c // eor x12, x12, x20
	WORD $0xca08014a // eor x10, x10, x8
	WORD $0x9b0a7d88 // mul x8, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0108 // eor x8, x8, x13
	WORD $0xa94d280c // ldp x12, x10, [x0, #208]
	WORD $0xca15018c // eor x12, x12, x21
	WORD $0xca09014a // eor x10, x10, x9
	WORD $0x9b0a7d89 // mul x9, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0129 // eor x9, x9, x13
	WORD $0x91038000 // add x0, x0, #0xe0
	WORD $0xd1038021 // sub x1, x1, #0xe0
	WORD $0xf103803f // cmp x1, #0xe0
	WORD $0x54fff52c // b.gt b8 <kernel+0xb8>
	// .Lone10:
	WORD $0xf101c03f // cmp x1, #0x70
	WORD $0x540005ad // b.le 2d0 <kernel+0x2d0>
	WORD $0xa940280c // ldp x12, x10, [x0]
	WORD $0xca0e018c // eor x12, x12, x14
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	WORD $0xa941280c // ldp x12, x10, [x0, #16]
	WORD $0xca0f018c // eor x12, x12, x15
	WORD $0xca04014a // eor x10, x10, x4
	WORD $0x9b0a7d84 // mul x4, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0084 // eor x4, x4, x13
	WORD $0xa942280c // ldp x12, x10, [x0, #32]
	WORD $0xca10018c // eor x12, x12, x16
	WORD $0xca05014a // eor x10, x10, x5
	WORD $0x9b0a7d85 // mul x5, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00a5 // eor x5, x5, x13
	WORD $0xa943280c // ldp x12, x10, [x0, #48]
	WORD $0xca11018c // eor x12, x12, x17
	WORD $0xca06014a // eor x10, x10, x6
	WORD $0x9b0a7d86 // mul x6, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00c6 // eor x6, x6, x13
	WORD $0xa944280c // ldp x12, x10, [x0, #64]
	WORD $0xca13018c // eor x12, x12, x19
	WORD $0xca07014a // eor x10, x10, x7
	WORD $0x9b0a7d87 // mul x7, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d00e7 // eor x7, x7, x13
	WORD $0xa945280c // ldp x12, x10, [x0, #80]
	WORD $0xca14018c // eor x12, x12, x20
	WORD $0xca08014a // eor x10, x10, x8
	WORD $0x9b0a7d88 // mul x8, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0108 // eor x8, x8, x13
	WORD $0xa946280c // ldp x12, x10, [x0, #96]
	WORD $0xca15018c // eor x12, x12, x21
	WORD $0xca09014a // eor x10, x10, x9
	WORD $0x9b0a7d89 // mul x9, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0129 // eor x9, x9, x13
	WORD $0x9101c000 // add x0, x0, #0x70
	WORD $0xd101c021 // sub x1, x1, #0x70
	// .Lafter11:
	WORD $0xca040042 // eor x2, x2, x4
	WORD $0xca0600a5 // eor x5, x5, x6
	WORD $0xca0800e7 // eor x7, x7, x8
	WORD $0xca090042 // eor x2, x2, x9
	WORD $0xca0700a5 // eor x5, x5, x7
	WORD $0xca050042 // eor x2, x2, x5
	// .Ltail4:
	WORD $0xf100403f // cmp x1, #0x10
	WORD $0x540005ed // b.le 3a8 <kernel+0x3a8>
	WORD $0xa940280c // ldp x12, x10, [x0]
	WORD $0xca10018c // eor x12, x12, x16
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	WORD $0xf100803f // cmp x1, #0x20
	WORD $0x540004ed // b.le 3a8 <kernel+0x3a8>
	WORD $0xa941280c // ldp x12, x10, [x0, #16]
	WORD $0xca10018c // eor x12, x12, x16
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	WORD $0xf100c03f // cmp x1, #0x30
	WORD $0x540003ed // b.le 3a8 <kernel+0x3a8>
	WORD $0xa942280c // ldp x12, x10, [x0, #32]
	WORD $0xca0f018c // eor x12, x12, x15
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	WORD $0xf101003f // cmp x1, #0x40
	WORD $0x540002ed // b.le 3a8 <kernel+0x3a8>
	WORD $0xa943280c // ldp x12, x10, [x0, #48]
	WORD $0xca0f018c // eor x12, x12, x15
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	WORD $0xf101403f // cmp x1, #0x50
	WORD $0x540001ed // b.le 3a8 <kernel+0x3a8>
	WORD $0xa944280c // ldp x12, x10, [x0, #64]
	WORD $0xca10018c // eor x12, x12, x16
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	WORD $0xf101803f // cmp x1, #0x60
	WORD $0x540000ed // b.le 3a8 <kernel+0x3a8>
	WORD $0xa945280c // ldp x12, x10, [x0, #80]
	WORD $0xca0f018c // eor x12, x12, x15
	WORD $0xca02014a // eor x10, x10, x2
	WORD $0x9b0a7d82 // mul x2, x12, x10
	WORD $0x9bca7d8d // umulh x13, x12, x10
	WORD $0xca0d0042 // eor x2, x2, x13
	// .Ltail1612:
	WORD $0x8b01000c // add x12, x0, x1
	WORD $0xf85f018a // ldur x10, [x12, #-16]
	WORD $0xf85f818b // ldur x11, [x12, #-8]
	WORD $0xca01014a // eor x10, x10, x1
	// .Ldone5:
	WORD $0xf940046c // ldr x12, [x3, #8]
	WORD $0xca0c014a // eor x10, x10, x12
	WORD $0xca02016b // eor x11, x11, x2
	WORD $0x9bcb7d45 // umulh x5, x10, x11
	WORD $0x9b0b7d44 // mul x4, x10, x11
	WORD $0xf9401c6a // ldr x10, [x3, #56]
	WORD $0xca0a0084 // eor x4, x4, x10
	WORD $0xca0c00a5 // eor x5, x5, x12
	WORD $0xca0100a5 // eor x5, x5, x1
	WORD $0x9b057c80 // mul x0, x4, x5
	WORD $0x9bc57c8d // umulh x13, x4, x5
	WORD $0xca0d0000 // eor x0, x0, x13
	MOVD R0, ret+16(FP)
	RET
