// Code generated by internal/asmgen. DO NOT EDIT.

//go:build !purego

package rapidhash

import "unsafe"

// Declarations for the arm64 kernels in the .s files beside this one.
// Which of them runs is decided in dispatch_arm64.go.

// sum64Rapid sum64Rapid hashes the n bytes at in under seed, whatever n is: every length class and the fold in one call..
//
//go:noescape
func sum64Rapid(in unsafe.Pointer, n int, seed uint64) uint64
